Issues/#20 tx structure
Equibit/equibit pull request #220
Opened 2018-11-21 19:40 UTC by r-soltani

Adding an Equibit specific transaction structure. 
see transaction.h and transaction.cpp for major changes to the structure.
Two new fields are introduced: EQBType (1 byte) and EQBPayload (object containing an empty vector)

2018-11-22 18:51 UTC, macterra requested changes
Checks are failing

2018-11-22 22:22 UTC, ealefad commented
there are 33 extra functional tests failing (on top of 17 disabled), should we disable or fix these tests?

2018-11-26 00:51 UTC, r-soltani commented
Functional checks can be disabled. They will be re-enabled together with other functional tests at the Stage branch

2018-11-26 19:17 UTC, ealefad approved these changes

2018-11-26 19:21 UTC, macterra commented on src/core_write.cpp
> +    entry.pushKV("EQB_type", (int8_t) tx.nEQBType);
Why insert EQB_type here rather than just before the payload?

2018-11-26 19:24 UTC, macterra commented on src/primitives/transaction.cpp
> +CTransaction::CTransaction() : vin(), vout(), nVersion(CTransaction::CURRENT_VERSION), nEQBType(EQBTypes::COINBASE), nEQBPayload(), nLockTime(0), hash() {}
Did you consider making the COINBASE type and empty payload the defaults for the ctor?

2018-11-26 21:43 UTC, r-soltani commented on src/core_write.cpp
> +    entry.pushKV("EQB_type", (int8_t) tx.nEQBType);
As discussed during our meeting, the type is read before parsing the vIn and vOut to be able to know the type of transactions we are expecting.

2018-11-26 21:44 UTC, r-soltani commented on src/primitives/transaction.cpp
> +CTransaction::CTransaction() : vin(), vout(), nVersion(CTransaction::CURRENT_VERSION), nEQBType(EQBTypes::COINBASE), nEQBPayload(), nLockTime(0), hash() {}
yes, this method is called during coinbase creation. The transactions are defined as coinbase unless their type is explicitly defined.

2018-11-26 21:48 UTC, macterra commented on src/core_write.cpp
> +    entry.pushKV("EQB_type", (int8_t) tx.nEQBType);
OK I'll be interested to see what difference it makes.

2018-11-26 21:50 UTC, macterra approved these changes

2018-11-26 21:56 UTC, merged