Issues/#121 reconf
Equibit/equibit pull request #226
Opened 2018-11-27 15:14 UTC by r-soltani

Reconfiguration for Equibit Core
- Ports
- Genesis text
- Genesis timestamp

2018-11-27 16:33 UTC, ealefad approved these changes

2018-11-27 17:18 UTC, macterra commented on eqb/ibmcloud/linux-ubuntu/docker/sha3/Dockerfile
> +ENV EQUIBIT_VERSION=0.3
Why reduce version numbers from 4 to 2?

2018-11-27 17:20 UTC, macterra commented on src/chainparams.cpp
> +        nDefaultPort = 8331;
Where did this value come from? What was the decision process?

2018-11-27 17:21 UTC, macterra commented on src/chainparams.cpp
>      const CScript genesisOutputScript = CScript() << ParseHex("04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f") <<
Should the script change?

2018-11-27 17:21 UTC, macterra commented on src/chainparams.cpp
>  static CBlock CreateGenesisBlock(uint32_t nTime, uint32_t nNonce, uint32_t nBits, int32_t nVersion, const CAmount& genesisReward)
What is being used for nTime?

2018-11-27 17:35 UTC, ealefad commented on eqb/ibmcloud/linux-ubuntu/docker/sha3/Dockerfile
> +ENV EQUIBIT_VERSION=0.3
Initially it was two digit number - "0.1", I first wanted to change it to something that correlates with what "equibitd --version" returns (which actually makes more sense) and added this four-field number, but at some point I thought that changing the format may cause modification of some of the scripts but I wanted to just check the build fast so I returned it to the initial format. However, this particular file is now being overwritten in my PR that brings these IBM Cloud scripts into the branch `issues/#219-stage` and I was going to add more relevant version format there

2018-11-27 18:27 UTC, r-soltani commented on src/chainparams.cpp
> +        nDefaultPort = 8331;
The port values, are the same as Bitcoin, decremented by one.
for example for mainnet: p2p port is 8333 and rpc port is 8332, and equibits p2p port is 8331 and equibit rpc port is 8330

2018-11-27 19:05 UTC, macterra commented on src/chainparams.cpp
> +        nDefaultPort = 8331;
Yes but why decrement rather than increment? Or why not 9333?

2018-11-27 19:06 UTC, r-soltani commented on src/chainparams.cpp
>  static CBlock CreateGenesisBlock(uint32_t nTime, uint32_t nNonce, uint32_t nBits, int32_t nVersion, const CAmount& genesisReward)
GMT: Sunday, November 25, 2018 5:02:59 PM

2018-11-27 19:19 UTC, r-soltani commented on src/chainparams.cpp
> +        genesis = CreateGenesisBlock(1543344629, nonce, nPoWTarget, 1, 50 * COIN);
GMT: Sunday, November 25, 2018 5:02:59 PM

2018-11-27 20:05 UTC, r-soltani commented on src/chainparams.cpp
> +        nDefaultPort = 8331;
either should work. I have not seen any conflict with the ports added now, and they follow a similar pattern as Bitcoins, and are in the same range of values. If we encounter any issue we can switch to a different port.

2018-11-27 20:06 UTC, r-soltani commented on src/chainparams.cpp
>      const CScript genesisOutputScript = CScript() << ParseHex("04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f") <<
The genesis block funds are reset to 0 and cannot be spent. The value here is the publickey of Satoshi' which we may change in the future iterations.

2018-11-29 12:34 UTC, macterra commented on src/chainparams.cpp
> +        nDefaultPort = 8331;
OK I guess we can defer the design.

2018-11-29 12:37 UTC, macterra commented on src/amount.h
> +static const CAmount   FIRST_BLOCK_REWARD = 131025772228310; // First BLock Reward = 1,000,000 + 2.1 * 10^7 / ( 1 + exp( 4.2 - (10^-5) * t ) ;   where t=1
Why not add first reward to genesis block? Won't we have to hard-code the first block reward block essentially adding a second genesis block?

2018-11-29 12:37 UTC, macterra commented on src/chainparams.cpp
>      const CScript genesisOutputScript = CScript() << ParseHex("04678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5f") <<
OK to defer.

2018-11-29 12:39 UTC, macterra requested changes
TBD resolve conflicts

2018-11-29 15:10 UTC, r-soltani commented on src/amount.h
> +static const CAmount   FIRST_BLOCK_REWARD = 131025772228310; // First BLock Reward = 1,000,000 + 2.1 * 10^7 / ( 1 + exp( 4.2 - (10^-5) * t ) ;   where t=1
The Genesis block cant be spend, whereas block 1 can.

2018-11-30 02:53 UTC, macterra approved these changes

2018-11-30 02:56 UTC, merged