#68 rename to equibit on config files: configure, makefile, gitignore
Equibit/equibit pull request #69
Opened 2018-08-28 21:34 UTC by r-soltani

Renaming the binaries from Bitcoin to Equibit

2018-08-29 12:10 UTC, macterra commented on configure.ac
> +BITCOIN_TX_NAME=equibit-tx
Why not change the names of the env variables too? (just curious)

2018-08-31 20:28 UTC, r-soltani commented on configure.ac
> +BITCOIN_TX_NAME=equibit-tx
that is my next step

2018-09-06 12:33 UTC, macterra requested changes
No checks yet. Maybe push a commit to trigger the continuous build?

2018-09-06 20:11 UTC, r-soltani commented
The check will fail because the functional tests(i.e. python codes) are referencing the bitcoin binaries instead of equibit binary. This issue will be resolved by the next commits.

2018-09-06 20:13 UTC, macterra approved these changes

2018-09-06 20:13 UTC, merged

2018-09-06 20:13 UTC, macterra commented
OK to make a temporary exception...