Issues/#83 rename to equibit
Equibit/equibit pull request #86
Opened 2018-09-07 18:35 UTC by r-soltani

As part of rebranding Bitcoin to Equibit (epic #60), the texts in the source codes that contain Bitcoin must change to Equibit. 
This PR also contains a Visual Studio Snippet to make it easier to add #ifdef preprocessors around code changes.

2018-09-10 14:31 UTC, ealefad approved these changes
Fails with only one error related to functional tests on Ubuntu which is predictable since functional test framework in /test/functional/ looks for 'bitcoind' executable. Windows doesn't run the functional tests so it's not failing in travis.

2018-09-14 14:43 UTC, macterra requested changes
Merge from dev to make the checks pass before merging

2018-09-14 14:49 UTC, KiarashN commented on src/rpc/mining.cpp
> -        throw JSONRPCError(RPC_CLIENT_NOT_CONNECTED, "Bitcoin is not connected!");
Make sure we don't change spaces to create "delete line"

2018-09-14 14:49 UTC, KiarashN commented on src/init.cpp
> -            gArgs.GetArg("-datadir", ""), fs::current_path().string());
Please make sure the spaces stays the same so it doesn't delete the line

2018-09-21 14:45 UTC, r-soltani commented on src/init.cpp
> -            gArgs.GetArg("-datadir", ""), fs::current_path().string());
fixed

2018-09-21 14:45 UTC, r-soltani commented on src/rpc/mining.cpp
> -        throw JSONRPCError(RPC_CLIENT_NOT_CONNECTED, "Bitcoin is not connected!");
fixed

2018-09-28 14:10 UTC, macterra commented on build_msvc/bitcoin_config.h
>  #define PACKAGE_BUGREPORT "https://github.com/bitcoin/bitcoin/issues"
Add copyright notice? (here and all C++ files touched in this PR)

2018-09-28 14:12 UTC, macterra commented on eqbtest/functional/rpc_users.py
>          rpcpassword = "rpcpassword=rpcpassword🔑"
Is there really a key icon in the password?

2018-09-28 14:14 UTC, macterra requested changes
Add copyright notices now or defer work with a new ticket?

2018-09-28 14:32 UTC, ealefad commented on eqbtest/functional/rpc_users.py
>          rpcpassword = "rpcpassword=rpcpassword🔑"
yes, it looks like there's a unicode sequence for a key emoji, UTF8="F0 9F 94 91"
http://www.endmemo.com/unicode/symbols_and_pictographs.php

2018-09-28 21:18 UTC, macterra commented on eqbtest/functional/rpc_users.py
>          rpcpassword = "rpcpassword=rpcpassword🔑"
cool!

2018-10-01 18:57 UTC, r-soltani commented on eqbtest/functional/feature_config_args.py
>          self.assert_start_raises_init_error(0, ['-datadir='+new_data_dir], 'Error: Specified data directory "' + new_data_dir + '" does not exist.')
@ealefad can you add the copyright statement to your python scripts

2018-10-02 12:34 UTC, macterra approved these changes

2018-10-03 01:10 UTC, merged